# Chap.-5 Regression-Model training & Evaluation

- ## Simple Linear Regression
    - ### Y = mX + b
    - Where Y = Dependent variable
        - X = Independent variable
        - m = slop (the value represent change in Y for a unit change in X)
        - b = Intercept (value of Y for X = 0)
            
- ## to cal
    - ### S1 : calculate mean of X and mean Y
    - ### S2 : cal deviation in X (X-mean(X))
        - ### cal deviation in Y (Y-mean(Y))
    - ### S3 : cal product of deviation in X and Y : (X-mean(X)) * (Y-mean(Y))
    - ### S4 : cal the square of deviation for X
    
- ## m = sum of product of deviation / sum of square of deviation for X
- ## b = mean of Y - (m * mean of X)

In [ ]:
=A2-$A$17

In [9]:
import pandas as pd
df = pd.read_csv('reg.csv')
df

x     y        dx    dy     product         dx2      m        b
0   15.000000  49.0 -4.933333  -7.8   38.480000   24.337778  1.893  19.0662
1   23.000000  63.0  3.066667   6.2   19.013333    9.404444    NaN      NaN
2   18.000000  58.0 -1.933333   1.2   -2.320000    3.737778    NaN      NaN
3   23.000000  60.0  3.066667   3.2    9.813333    9.404444    NaN      NaN
4   24.000000  58.0  4.066667   1.2    4.880000   16.537778    NaN      NaN
5   22.000000  61.0  2.066667   4.2    8.680000    4.271111    NaN      NaN
6   22.000000  60.0  2.066667   3.2    6.613333    4.271111    NaN      NaN
7   19.000000  63.0 -0.933333   6.2   -5.786667    0.871111    NaN      NaN
8   19.000000  60.0 -0.933333   3.2   -2.986667    0.871111    NaN      NaN
9   16.000000  52.0 -3.933333  -4.8   18.880000   15.471111    NaN      NaN
10  24.000000  62.0  4.066667   5.2   21.146667   16.537778    NaN      NaN
11  11.000000  30.0 -8.933333 -26.8  239.413333   79.804444    NaN      NaN
12  24.000000  59.0  4.066667   2.2    8.946667   16.537778    NaN      NaN
13  16.000000  49.0 -3.933333  -7.8   30.680000   15.471111    NaN      NaN
14  23.000000  68.0  3.066667  11.2   34.346667    9.404444    NaN      NaN
15  19.933333  56.8       NaN   NaN  429.800000  226.933333    NaN      NaN

In [3]:
import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.read_csv('reg.csv')

LR = LinearRegression()
LR.fit(df[['x']],df[['y']])

print(LR.coef_)
print(LR.intercept_)

[[1.8939483]]
[19.0472973]


In [10]:
import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.read_csv('reg.csv')

LR = LinearRegression()
LR.fit(df[['x']],df[['y']])

ypred = LR.predict(df[['x']])
print(ypred)
print('-----------------------')
print(LR.coef_)
print(LR.intercept_)

[[47.45652174]
 [62.60810811]
 [53.13836663]
 [62.60810811]
 [64.5020564 ]
 [60.71415981]
 [60.71415981]
 [55.03231492]
 [55.03231492]
 [49.35047004]
 [64.5020564 ]
 [39.88072856]
 [64.5020564 ]
 [49.35047004]
 [62.60810811]
 [56.79999999]]
-----------------------
[[1.8939483]]
[19.0472973]


- ## fit function - to learn model

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.DataFrame({'y':[140,155,159,179,192,200,212,215],
                 'X1':[60,62,67,70,71,72,75,78]})
LR = LinearRegression()
LR.fit(df[['y']],df[['X1']])

ypred = LR.predict(df[['y']])
print(ypred)
print('-----------------------')
print(LR.coef_)
print(LR.intercept_)

[[60.50992282]
 [63.71416759]
 [64.56863286]
 [68.84095921]
 [71.61797133]
 [73.32690187]
 [75.89029768]
 [76.53114664]]
-----------------------
[[0.21361632]]
[30.60363837]


In [14]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df = pd.DataFrame({
    "x": [15, 23, 18, 23, 24, 22, 22, 19, 19, 16, 24, 11, 24, 16, 23],
    "y": [49, 63, 58, 60, 58, 61, 60, 63, 60, 52, 62, 30, 59, 49, 68]
})
x = df[['x']]
y = df[['y']]

x_train, x_test, y_train, y_test = train_test_split(x,y)

LR = LinearRegression()
LR.fit(x_train,y_train)

ypred = LR.predict(x_test)
print(ypred)
print('-----------------------')
print(LR.coef_)
print(LR.intercept_)

print('-----------------------')
print(x_train.shape)
print(x_test.shape)
print('-----------------------')
print(y_train.shape)
print(y_test.shape)

[[57.12068966]
 [63.47126437]
 [52.04022989]
 [46.95977011]]
-----------------------
[[1.27011494]]
[32.98850575]
-----------------------
(11, 1)
(4, 1)
-----------------------
(11, 1)
(4, 1)


- ## train_test_split(x,y) first col must be 2-D
- ## x_train, x_test, y_train, y_test = train_test_split(x,y)
- ## sequence must be followed

In [16]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df = pd.DataFrame({
    "x": [15, 23, 18, 23, 24, 22, 22, 19, 19, 16, 24, 11, 24, 16, 23],
    "y": [49, 63, 58, 60, 58, 61, 60, 63, 60, 52, 62, 30, 59, 49, 68]
})
x = df[['x']]
y = df[['y']]

x_train, x_test, y_train, y_test = train_test_split(x,y, train_size=0.5)

LR = LinearRegression()
LR.fit(x_train,y_train)

ypred = LR.predict(x_test)
print(ypred)
print('-----------------------')
print(LR.coef_)
print(LR.intercept_)

print('-----------------------')
print(x_train.shape)
print(x_test.shape)
print('-----------------------')
print(y_train.shape)
print(y_test.shape)

[[51.72988506]
 [60.71264368]
 [44.24425287]
 [63.70689655]
 [56.22126437]
 [63.70689655]
 [50.23275862]
 [54.72413793]]
-----------------------
[[1.49712644]]
[27.77586207]
-----------------------
(7, 1)
(8, 1)
-----------------------
(7, 1)
(8, 1)


In [17]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df = pd.DataFrame({
    "x": [15, 23, 18, 23, 24, 22, 22, 19, 19, 16, 24, 11, 24, 16, 23],
    "y": [49, 63, 58, 60, 58, 61, 60, 63, 60, 52, 62, 30, 59, 49, 68]
})
x = df[['x']]
y = df[['y']]

x_train, x_test, y_train, y_test = train_test_split(x,y, train_size=0.9)

LR = LinearRegression()
LR.fit(x_train,y_train)

ypred = LR.predict(x_test)
print(ypred)
print('-----------------------')
print(LR.coef_)
print(LR.intercept_)

print('-----------------------')
print(x_train.shape)
print(x_test.shape)
print('-----------------------')
print(y_train.shape)
print(y_test.shape)

[[47.05376344]
 [64.95698925]]
-----------------------
[[1.98924731]]
[17.21505376]
-----------------------
(13, 1)
(2, 1)
-----------------------
(13, 1)
(2, 1)


In [19]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df = pd.DataFrame({
    "x": [15, 23, 18, 23, 24, 22, 22, 19, 19, 16, 24, 11, 24, 16, 23],
    "y": [49, 63, 58, 60, 58, 61, 60, 63, 60, 52, 62, 30, 59, 49, 68]
})
x = df[['x']]
y = df[['y']]

x_train, x_test, y_train, y_test = train_test_split(x,y, train_size=0.5)

LR = LinearRegression()
LR.fit(x_train,y_train)

ypred = LR.predict(x_test)
print(ypred)

print("x_train")
print(x_train)
print("x_test")
print(x_test)

[[47.3740458 ]
 [62.39694656]
 [53.63358779]
 [61.14503817]
 [61.14503817]
 [57.38931298]
 [53.63358779]
 [63.64885496]]
x_train
     x
4   24
2   18
10  24
8   19
1   23
14  23
0   15
x_test
     x
11  11
3   23
13  16
6   22
5   22
7   19
9   16
12  24


In [26]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df = pd.DataFrame({
    "x": [15, 23, 18, 23, 24, 22, 22, 19, 19, 16, 24, 11, 24, 16, 23],
    "y": [49, 63, 58, 60, 58, 61, 60, 63, 60, 52, 62, 30, 59, 49, 68]
})
x = df[['x']]
y = df[['y']]

x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=3)

LR = LinearRegression()
LR.fit(x_train,y_train)

ypred = LR.predict(x_test)
print(ypred)
print('-----------------------')
print(LR.coef_)
print(LR.intercept_)

print("-----------------------\nx_train")
print(x_train)
print("-----------------------\nx_test")
print(x_test)

print('-----------------------')
print(x_train.shape)
print(x_test.shape)
print('-----------------------')
print(y_train.shape)
print(y_test.shape)

[[67.67663344]
 [67.67663344]
 [65.393134  ]
 [63.10963455]]
-----------------------
[[2.28349945]]
[12.87264673]
-----------------------
x_train
     x
2   18
11  11
7   19
5   22
0   15
14  23
13  16
3   23
9   16
8   19
10  24
-----------------------
x_test
     x
12  24
4   24
1   23
6   22
-----------------------
(11, 1)
(4, 1)
-----------------------
(11, 1)
(4, 1)


In [24]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df = pd.DataFrame({
    "x": [15, 23, 18, 23, 24, 22, 22, 19, 19, 16, 24, 11, 24, 16, 23],
    "y": [49, 63, 58, 60, 58, 61, 60, 63, 60, 52, 62, 30, 59, 49, 68]
})
x = df[['x']]
y = df[['y']]

x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=4)

LR = LinearRegression()
LR.fit(x_train,y_train)

ypred = LR.predict(x_test)
print(ypred)
print('-----------------------')
print(LR.coef_)
print(LR.intercept_)

print("-----------------------\nx_train")
print(x_train)
print("-----------------------\nx_test")
print(x_test)

print('-----------------------')
print(x_train.shape)
print(x_test.shape)
print('-----------------------')
print(y_train.shape)
print(y_test.shape)

[[66.26730564]
 [46.99254526]
 [61.98402556]
 [64.1256656 ]]
-----------------------
[[2.14164004]]
[14.86794462]
-----------------------
x_train
     x
4   24
9   16
11  11
2   18
14  23
13  16
8   19
1   23
5   22
7   19
10  24
-----------------------
x_test
     x
12  24
0   15
6   22
3   23
-----------------------
(11, 1)
(4, 1)
-----------------------
(11, 1)
(4, 1)


In [27]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df = pd.DataFrame({
    "x": [15, 23, 18, 23, 24, 22, 22, 19, 19, 16, 24, 11, 24, 16, 23],
    "y": [49, 63, 58, 60, 58, 61, 60, 63, 60, 52, 62, 30, 59, 49, 68]
})
x = df[['x']]
y = df[['y']]

x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=5)

LR = LinearRegression()
LR.fit(x_train,y_train)

ypred = LR.predict(x_test)
print(ypred)
print('-----------------------')
print(LR.coef_)
print(LR.intercept_)

print("-----------------------\nx_train")
print(x_train)
print("-----------------------\nx_test")
print(x_test)

print('-----------------------')
print(x_train.shape)
print(x_test.shape)
print('-----------------------')
print(y_train.shape)
print(y_test.shape)

[[59.62008734]
 [61.57292576]
 [53.76157205]
 [51.80873362]]
-----------------------
[[1.95283843]]
[16.65764192]
-----------------------
x_train
     x
10  24
14  23
11  11
4   24
8   19
9   16
0   15
12  24
6   22
13  16
3   23
-----------------------
x_test
    x
5  22
1  23
7  19
2  18
-----------------------
(11, 1)
(4, 1)
-----------------------
(11, 1)
(4, 1)


In [28]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df = pd.DataFrame({
    "x": [15, 23, 18, 23, 24, 22, 22, 19, 19, 16, 24, 11, 24, 16, 23],
    "y": [49, 63, 58, 60, 58, 61, 60, 63, 60, 52, 62, 30, 59, 49, 68]
})
x = df[['x']]
y = df[['y']]

x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=42)

LR = LinearRegression()
LR.fit(x_train,y_train)

ypred = LR.predict(x_test)
print(ypred)
print('-----------------------')
print(LR.coef_)
print(LR.intercept_)

print("-----------------------\nx_train")
print(x_train)
print("-----------------------\nx_test")
print(x_test)

print('-----------------------')
print(x_train.shape)
print(x_test.shape)
print('-----------------------')
print(y_train.shape)
print(y_test.shape)

[[59.99256506]
 [59.06319703]
 [59.80669145]
 [59.99256506]]
-----------------------
[[0.18587361]]
[57.01858736]
-----------------------
x_train
     x
5   22
8   19
2   18
1   23
14  23
4   24
7   19
10  24
12  24
3   23
6   22
-----------------------
x_test
     x
9   16
11  11
0   15
13  16
-----------------------
(11, 1)
(4, 1)
-----------------------
(11, 1)
(4, 1)


In [34]:
import sklearn
help(sklearn)

Help on package sklearn:

NAME
    sklearn

DESCRIPTION
    Machine learning module for Python
    
    sklearn is a Python module integrating classical machine
    learning algorithms in the tightly-knit world of scientific Python
    packages (numpy, scipy, matplotlib).
    
    It aims to provide simple and efficient solutions to learning problems
    that are accessible to everybody and reusable in various contexts:
    machine-learning as a versatile tool for science and engineering.
    
    See http://scikit-learn.org for complete documentation.

PACKAGE CONTENTS
    __check_build (package)
    _build_utils (package)
    _config
    _distributor_init
    _isotonic
    _loss (package)
    base
    calibration
    cluster (package)
    compose (package)
    conftest
    covariance (package)
    cross_decomposition (package)
    datasets (package)
    decomposition (package)
    discriminant_analysis
    dummy
    ensemble (package)
    exceptions
    experimental (package)
    ext

In [36]:
import sklearn
help(sklearn.model_selection.train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, **options)
    Split arrays or matrices into random train and test subsets
    
    Quick utility that wraps input validation and
    ``next(ShuffleSplit().split(X, y))`` and application to input data
    into a single call for splitting (and optionally subsampling) data in a
    oneliner.
    
    Read more in the :ref:`User Guide <cross_validation>`.
    
    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.
    
    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to the
        complement of the train size. If ``train_size`` is also Non

## P.b. 195

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

x = np.array([5, 15, 25, 35, 45, 55]).reshape(-1,1)
y = np.array([5, 20, 14, 32, 22, 38])

LR = LinearRegression()
LR.fit(x,y)

x_test = np.arange(5).reshape(-1,1)
print(x_test)

ypred = LR.predict(x_test)
print(ypred)
print(LR.coef_)
print(LR.intercept_)

# Mean Square Error

- ## In MCQ
- ### it's a matrix to evaluate the performance of predictive models
- ### it measure the avg. of the square diffreneces between predicted values & target values.
- ### lower mse indicates that the models prediction are closure to the true values reflecting better overall performance.